### ISSUE TITLE
building and running on Linux distros with gcc < 4.8

### ISSUE THREAD

**Issue by ink1** [gaow/SEQPower#3]
Hello, Gao
Do you have any suggestions on building and running SEQPower on Linux distros with default gcc < 4.8?
After installing anaconda/2.3.0 on CentOS 6.4, I can build SEQPower as long as I use gcc/4.8.3 which I had made available on the system but which is not the default. However when spower is run it segfaults as soon as CalculatorOpt is imported
from spower.opts import CalculatorOpt

Obviously when I set gcc/4.8.3 environment, LD_LIBRARY_PATH and PATH are set accordingly but I suspect this interferes with Anaconda. Generally it does not even like when PYTHONPATH is set which is necessary for SEQPower to work.

Thanks
Igor

**Comment by gaow** [comment]
SEQPower is best executed with Docker. Docker image for `SEQPower` and instruction to run `SEQPower` from docker has been updated [here](http://bioinformatics.org/spower/installation).

**Comment by ink1** [comment]
We do not allow Docker on our HPC clusters. However we had some successes running Singularity. Conversion of Docker images to Singularity images is possible either locally or directly from Docker hub.
