### ISSUE TITLE
problem installing on ubuntu 14.04LTS

### ISSUE THREAD

**Issue by fbrcdnj** [gaow/SEQPower#4]
Hi,
I got an error installing seqpower which did not recognize conda installed, so I manually installed simuPOP. Yet, after this I get an error which I do not understand, as reported below. Could you give me some hints please?
Best regards, 
Fab.

Downloading cstatgen library ...
Installing cstatgen library ...
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
src/cstatgen_py2.cxx:155:21: fatal error: Python.h: No such file or directory
 # include <Python.h>
                     ^
compilation terminated.
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
running install
running build
running build_py
copying src/**init**.py -> build/lib.linux-x86_64-2.7/spower
running build_ext
building 'spower.simulator._loci' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isrc -Isrc/simulator -Isrc/gsl -I/usr/include/python2.7 -c src/simulator/loci_wrap_py2.cpp -o build/temp.linux-x86_64-2.7/src/simulator/loci_wrap_py2.o -O3 -std=c++11
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isrc -Isrc/simulator -Isrc/gsl -I/usr/include/python2.7 -c src/simulator/loci.cpp -o build/temp.linux-x86_64-2.7/src/simulator/loci.o -O3 -std=c++11
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isrc -Isrc/simulator -Isrc/gsl -I/usr/include/python2.7 -c src/gsl/error.c -o build/temp.linux-x86_64-2.7/src/gsl/error.o -O3 -std=c++11
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isrc -Isrc/simulator -Isrc/gsl -I/usr/include/python2.7 -c src/gsl/rng/rng.c -o build/temp.linux-x86_64-2.7/src/gsl/rng/rng.o -O3 -std=c++11
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isrc -Isrc/simulator -Isrc/gsl -I/usr/include/python2.7 -c src/gsl/rng/default.c -o build/temp.linux-x86_64-2.7/src/gsl/rng/default.o -O3 -std=c++11
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isrc -Isrc/simulator -Isrc/gsl -I/usr/include/python2.7 -c src/gsl/rng/mt.c -o build/temp.linux-x86_64-2.7/src/gsl/rng/mt.o -O3 -std=c++11
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isrc -Isrc/simulator -Isrc/gsl -I/usr/include/python2.7 -c src/gsl/rng/types.c -o build/temp.linux-x86_64-2.7/src/gsl/rng/types.o -O3 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isrc -Isrc/simulator -Isrc/gsl -I/usr/include/python2.7 -c src/gsl/randist/gauss.c -o build/temp.linux-x86_64-2.7/src/gsl/randist/gauss.o -O3 -std=c++11
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isrc -Isrc/simulator -Isrc/gsl -I/usr/include/python2.7 -c src/gsl/randist/gausszig.c -o build/temp.linux-x86_64-2.7/src/gsl/randist/gausszig.o -O3 -std=c++11
src/simulator/loci_wrap_py2.cpp:155:21: fatal error: Python.h: No such file or directory
 # include <Python.h>
                     ^
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
compilation terminated.
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
src/umich/clusters/HaploFamily.cpp: In member function ‘bool FamilyHaplos::RetrieveGraph(bool)’:
src/umich/clusters/HaploFamily.cpp:417:10: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wparentheses]
       if (likelihood == 0.0)
          ^
src/umich/clusters/HaploFamily.cpp: In member function ‘FounderGraph\* FounderGraph::Append(IntArray_, IntArray_, LongArray_, LongArray_, double, BasicHash*)’:
src/umich/clusters/HaploFamily.cpp:528:7: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wparentheses]
    if (current->graph != NULL)
       ^

**Comment by gaow** [comment]
Sorry to hear that. Would you try:

```
sudo apt-get install python-dev
```

Then run the installer again?

**Comment by fbrcdnj** [comment]
Thank you for the quick answer. 
I installed python-dev and the process ended even if I got many warnings. Yet, trying to run spower, I now get the following error:

:~/soft/seqpower$ spower
Traceback (most recent call last):
  File "/usr/local/bin/spower", line 10, in <module>
    from spower.opts import CalculatorOpt
  File "/usr/local/lib/python2.7/dist-packages/spower/opts.py", line 13, in <module>
    from spower.calculator.manager import Executor, showTests, showFields
  File "/usr/local/lib/python2.7/dist-packages/spower/calculator/manager.py", line 20, in <module>
    from spower.calculator.algorithms import *
  File "/usr/local/lib/python2.7/dist-packages/spower/calculator/algorithms.py", line 21, in <module>
    from spower.calculator.vat import VATWorker
  File "/usr/local/lib/python2.7/dist-packages/spower/calculator/vat.py", line 12, in <module>
    from spower.vat.tester import *
  File "/usr/local/lib/python2.7/dist-packages/spower/vat/tester.py", line 38, in <module>
    import statsmodels.api as sm
ImportError: No module named statsmodels.api

**Comment by gaow** [comment]
SEQPower is best executed with Docker. Docker image for `SEQPower` and instruction to run `SEQPower` from docker has been updated [here](http://bioinformatics.org/spower/installation).
