### ISSUE TITLE
docker volume permissions

### ISSUE THREAD

**Issue by aylwyn** [gaow/SEQPower#8]
On ubuntu 14.4LTS:

At present when I run e.g. the tutorial command
docker run -v $PWD:/home/seqx/data gaow/seqx spower LOGIT Kryukov2009European1800.sfs --sample_size 1000 --OR_rare_detrimental 1.5 --method CFisher -r 1000 -j 4 -l 1 -o exercise
I get the following file permission error:
ERROR: [Errno 13] Permission denied: '/home/seqx/data/exercise.log'

This does not seem to be a general docker problem, e.g. I can run 
docker run -v $PWD:/foo ubuntu touch /foo/bar
without any problems. (Other than that foo is owned by root but that's a more general docker issue.)

**Comment by aylwyn** [comment]
(should add, I also compiled spower from source and it seems to be working ok. But would be nice to have the docker container working.)

**Comment by gaow** [comment]
SEQPower is best executed with Docker. Docker image for `SEQPower` and instruction to run `SEQPower` from docker has been updated [here](http://bioinformatics.org/spower/installation).
