### ISSUE TITLE
Problem using spower via mac from docker : SKAT method error

### ISSUE THREAD

**Issue by arppa99100** [gaow/SEQPower#9]
Hi,

When I run the SEQpower using SKAT method, the program tries to install SKAT R library, fails and freezes. It seems to try to install the library to lib="/home/seqx/.spower/Rlib" (Docker path?). Other methods work just fine. It didn't help to install the SKAT library to my Mac.

Error:
ValueError: Cannot auto-install / load R library SKAT: Execution of command '['R', '-e', 'install.packages("/tmp/SKAT_0.93.tar.gz", repos = NULL, type = "source", lib="/home/seqx/.spower/Rlib")']' failed: [Errno 2] No such file or directory

The Command used:
spower LOGIT Kryukov2009European1800.sfs --sample_size 1000 --OR_rare_detrimental 1.5 --met "SKAT disease" -r 1000 -j 4 -l 1 -o exercise

**Comment by gaow** [comment]
This issue has been fixed in the latest docker image for `SEQPower` and instruction to run `SEQPower` from docker has been updated [here](http://bioinformatics.org/spower/installation).
